ScreenSize=get(0,'ScreenSize');
d.MainHeit=300;
d.MainWidth=200;
h.Main=figure('Position',[100,300,d.MainWidth,d.MainHeit]);
set(h.Main,'NumberTitle','off');
set(h.Main,'MenuBar','none');
set(h.Main,'Name','Simple FRAP analyzer');
BkGrColor=get(h.Main,'Color');
%Controls
h.OpenImageBut=uicontrol(h.Main, 'Style','pushbut',...
                              'String','Open',...
                              'TooltipString','Open folder with images',...
                              'Position',[10,d.MainHeit-70,120,30],...
                              'Callback','CallBkOpenImageBut');
%Run
h.RunBut=uicontrol(h.Main, 'Style','pushbut',...
                              'String','Run',...
                              'TooltipString','Run calculations',...
                              'Position',[10,d.MainHeit-180,120,30],...
                              'Callback','CallBkRunBut');
%Save
h.SaveBut=uicontrol(h.Main, 'Style','pushbut',...
                              'String','Save',...
                              'TooltipString','Save figure',...
                              'Position',[10,d.MainHeit-220,120,30],...
                              'Callback','CallBkRunBut');
%Dinit
h.DinitText=uicontrol(h.Main, 'Style','text',...
                    'String','Dinit = ',...
                    'TooltipString','Initial guess of diffudion coefficient',...
                    'BackgroundColor',BkGrColor,...
                    'HorizontalAlignment','Right',...
                    'Position',[10,d.MainHeit-105,70,20]);
h.DinitEdit=uicontrol(h.Main, 'Style','edit',...
                    'String','1e-12',...
                    'TooltipString','Initial guess of diffudion coefficient',...
                    'Value',1e-12,...
                    'Position',[80,d.MainHeit-100,50,20],...
                    'Callback','CallBkDinitdEdit');
h.DinitUnitsText=uicontrol(h.Main, 'Style','text',...
                    'String',' m^2/s',...
                    'TooltipString','Initial guess of diffudion coefficient',...
                    'BackgroundColor',BkGrColor,...
                    'HorizontalAlignment','Left',...
                    'Position',[130,d.MainHeit-105,70,20]);
%Pixel size
h.PixelSizeText=uicontrol(h.Main, 'Style','text',...
                    'String','PixelSize= ',...
                    'TooltipString','PixelSize',...
                    'BackgroundColor',BkGrColor,...
                    'HorizontalAlignment','Right',...
                    'Position',[10,d.MainHeit-125,70,20]);
h.PixelSizeEdit=uicontrol(h.Main, 'Style','edit',...
                    'String','0.5e-6',...
                    'TooltipString','PixelSize',...
                    'Value',0.5e-6,...
                    'Position',[80,d.MainHeit-120,50,20],...
                    'Callback','CallBkThresholdEdit');
h.PixelSizeUnitsText=uicontrol(h.Main, 'Style','text',...
                    'String',' m',...
                    'TooltipString','PixelSize',...
                    'BackgroundColor',BkGrColor,...
                    'HorizontalAlignment','Left',...
                    'Position',[130,d.MainHeit-125,70,20]);
%n
h.nText=uicontrol(h.Main, 'Style','text',...
                    'String','n= ',...
                    'TooltipString','Number of terms in solution',...
                    'BackgroundColor',BkGrColor,...
                    'HorizontalAlignment','Right',...
                    'Position',[10,d.MainHeit-145,70,20]);
h.nEdit=uicontrol(h.Main, 'Style','edit',...
                    'String','50',...
                    'TooltipString','Number of terms in solution',...
                    'Value',50,...
                    'Position',[80,d.MainHeit-140,50,20],...
                    'Callback','CallBkThresholdEdit');
